version: '3.8'

services:
  fastapi-back:
    build: ./back
    container_name: security_back_server
    restart: always
    ports:
      - "8000:8000"

  streamlit-front:
    build: ./front
    container_name: security_front_server
    restart: always
    ports:
      - "80:8501"
    depends_on:
      - fastapi-back